### PR TITLE
add "do not populate" component marking

### PR DESCRIPTION
**Pull request by eqvinox**
Only in the schematic editor for now;  marks an entire component (with
all its symbols) as DNP.  Drawn grayed out with an X over it (calculated
from the bounding box, occasionally looks a bit weird but eh.)

TBD/Future:
- ~add BOM export option to exclude DNP parts~ done
- visualize in board editor & assembly export

screenshot for posterity:
https://aurora.nox.tf/tmp/horizon_dnp.png

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Cool! It's really reassuring to know that other people than me can make non-trivial changes as well.

Some minor things:

I think that drawing symbols in grey and adding the cross is overdoing it bit. The cross by itself is probably fine. I've had in mind to use the grey style to indicate components that aren't yet placed on the board at some point in the future.

A simple tool to set/clear the unpopulate flag would be nice as it allows to modify this flag more directly (context menu or shortcut). See https://github.com/horizon-eda/horizon/blob/master/src/core/tools/tool_fix.cpp for a similar tool.

**Comment by eqvinox** [comment]
updated; I left the code for drawing symbols in a different colors in a separate commit so you can reuse it for the "not placed yet" indication.

> Cool! It's really reassuring to know that other people than me can make non-trivial changes as well.

That's pretty funny because I'm not actually a C++ developer ;D.  Then again I would consider this PR a trivial change really.

**Comment by eqvinox** [comment]
added BOM export checkbox for DNP parts

**Comment by eqvinox** [comment]
Not sure why the AppVeyor CI says "Build has been cancelled by a user.", at least I didn't do anything there.

**Comment by carrotIndustries** [comment]
LGTM, as far as I can tell, the only real thing missing is supporting the new flag in the pick&place export?

**Comment by carrotIndustries** [comment]
One more thing: A common feature among more upmarket EDA software is support for variants.

Suppose you're building something that could be made as either a one or two channel variant. By supporting variants we could represent this in the design data.

Unfortunately, this gets rather unwieldy if we have two or more dimensions that could be varied independently, such as channel count and number of memory chips populated. To elegantly solve this case, we'd need something like meta-variants: One for channel count, one for the memory. The meta variants could then be merged into actual variants that'll get made.

Anyhow, the simple 'do not place' flag is probably enough for most people's use cases.

**Comment by eqvinox** [comment]
> LGTM, as far as I can tell, the only real thing missing is supporting the new flag in the pick&place export?

Oh yeah I totally forgot about that since I haven't used it yet.  I can probably wire that up quickly.

What's also left to do is board/assembly view support; I have a hack but I'm not particularly happy about it and I think this is something for the "next" PR.

> One more thing: A common feature among more upmarket EDA software is support for variants.

I think a good way of doing this without getting overly complex might be with plain old tagging things.  Independent tags can represent orthogonal "dimensions" easily, and if needed there can be an analog of "design rules" that describe tag interdependencies (e.g. "channel3" tag requires "channel2" tag, "230V" tag conflicts with "115V" tag, etc.)

**Comment by eqvinox** [comment]
(add:) Good "Variant" support probably needs some sensible way of swapping out different parts in the same footprint, e.g. for different resistor values or even different IC variants...

**Comment by eqvinox** [comment]
PNP export now has a checkbox like BOM export.

Also, thanks for the quick PDF export fix :)

**Comment by carrotIndustries** [comment]
I think what we have at this point is a good enough for most use cases, so I merged it.

**Pull request merged**
