### PR TITLE
macOS Support (frist steps)

### PR DESCRIPTION
**Pull request by phlmn**
Hey,
I managed to get something working on macOS.

For this I had to:
- update nlohmann json
- update the Makefile
- import libuuid from `uuid/uuid.h` instead of `uuid.h`
- write `get_exe_dir()` for macOS

Unfortunately the board viewer does not work yet. `glLineWidth(…)` and `glBlitFrameBuffer(…)` are causing an error. By removing `glLineWidth(…)` and drawing directly to the screen instead of using `glBlitFrameBuffer(…)` the board viewer does start. Debugging OpenGL is not much fun, maybe someone has an idea.

Some potentially useful apitrace output:
```
$ ./apitrace replay horizon-imp.5.trace
/Users/phlmn/Coding/apitrace/build/../../horizon/horizon-imp
1 @0 CGLRetainPixelFormat(pix = 0x7ff682f98870) = 0x7ff682f98870
1: warning: unsupported CGLRetainPixelFormat call
2 @0 CGLReleasePixelFormat(pix = 0x7ff682f98870)
2: warning: unsupported CGLReleasePixelFormat call
4 @0 CGLRetainContext(ctx = 0x7ff68406a400) = 0x7ff68406a400
4: warning: unsupported CGLRetainContext call
5 @0 CGLReleaseContext(ctx = 0x7ff68406a400)
5: warning: unsupported CGLReleaseContext call
6 @0 CGLReleasePixelFormat(pix = 0x7ff682f98870)
6: warning: unsupported CGLReleasePixelFormat call
14 @0 CGLRetainPixelFormat(pix = 0x7ff682e7a510) = 0x7ff682e7a510
14: warning: unsupported CGLRetainPixelFormat call
15 @0 CGLReleasePixelFormat(pix = 0x7ff682e7a510)
15: warning: unsupported CGLReleasePixelFormat call
17 @0 CGLRetainContext(ctx = 0x7ff68492f800) = 0x7ff68492f800
17: warning: unsupported CGLRetainContext call
18 @0 CGLReleaseContext(ctx = 0x7ff68492f800)
18: warning: unsupported CGLReleaseContext call
19 @0 CGLReleasePixelFormat(pix = 0x7ff682e7a510)
19: warning: unsupported CGLReleasePixelFormat call
GL_RENDERER: Intel(R) Iris(TM) Graphics 550
GL_VENDOR: Intel Inc.
477 @0 glLinkProgram(program = 8)
477: warning: WARNING: Output of vertex shader 'oid_to_geom' not read by geometry shader
WARNING: Output of vertex shader 'lod_to_geom' not read by geometry shader

509 @0 glLinkProgram(program = 9)
509: warning: WARNING: Output of vertex shader 'oid_to_geom' not read by geometry shader

541 @0 glLinkProgram(program = 10)
541: warning: WARNING: Output of vertex shader 'oid_to_geom' not read by geometry shader
WARNING: Output of geometry shader 'flags_to_fragment' not read by fragment shader

573 @0 glLinkProgram(program = 11)
573: warning: WARNING: Output of vertex shader 'oid_to_geom' not read by geometry shader
WARNING: Output of geometry shader 'flags_to_fragment' not read by fragment shader

GL_RENDERER: Intel(R) Iris(TM) Graphics 550
GL_VENDOR: Intel Inc.
1299 @0 glLineWidth(width = 2)
1299: warning: glGetError(glLineWidth) = GL_INVALID_VALUE
1311 @0 glLineWidth(width = 2)
1311: warning: glGetError(glLineWidth) = GL_INVALID_VALUE
Rendered 0 frames in 0.241093 secs, average of 0 fps
```

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Uh, looks like gtk finally gained OpenGL support on quartz and you're the first one to actually use it aside from gtk's OpenGL demo.

See https://gitlab.gnome.org/GNOME/gtk/commit/f34709807f5b2f56a86bc3127e59084936ce57fe and the associated issue. It's probably the best to reach out gtk folks involved in that matter.

**Comment by rroohhh** [comment]
The `glLineWidth` issue is probably because only width `1` is actually guaranteed to be supportedand. (See https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glLineWidth.xhtml)

**Comment by phlmn** [comment]
@carrotIndustries To keep this PR small I think it can get reviewed and eventually merged. This should not affect other platforms. 

I created an Issue for on overview of macOS Support (#271).

**Comment by carrotIndustries** [comment]
In order to properly merge this, it's best to split the PR into it's parts: update json.hpp, the `get_exe_dir` thing and the other random bits and pieces.

**Comment by phlmn** [comment]
@carrotIndustries will do!

**Comment by phlmn** [comment]
Splitted into multiple PRs.

**Pull request closed without merging**
