### PR TITLE
Spacebar menu hint

### PR DESCRIPTION
**Pull request by carrotIndustries**
As discussed in #119, I've had the idea to show some kind of hint to make newcomers aware of the spacebar menu. Current design:

2020-05-14-223120_538x482_scrot

Things left to figure out:
 - When to show this hint? I've had in mind to show this if the spacebar menu hasn't been opened within 30(?) seconds after opening an editor
 - When not to show this hint? Set a a flag that the spacebar menu has been opened at least once and not show it?

Any thoughts?

### CODE REVIEW

**Comment by fruchti** [comment]
I like the design! IMHO, it would feel less unexpected if it was shown immediately on the first start, though. With the time delay it might happen that a new user opens an example schematic, zooms and pans around and has the tip window pop up unrequested, maybe even closing it by accident without getting a chance to read the text.

**Comment by endofexclusive** [comment]
Nice.
- when to show
  - Agree about showing it immediately on the first start.
  - When pressing F1?

- when not to show
  - Anytime after the first start.

The spacebar menu is powerful and effective. I have found myself hitting space in all kinds of other applications to invoke a command, just to realize that I was not in Horizon.

About the hit design. How about adding an image of an actual spacebar? Now there is the light bulb icon so the user might try to find that one in the GUI. The text "Press space" could be "Press the space bar" to prevent mixing it up with the schematic work space for example.

**Comment by carrotIndustries** [comment]
I wanted to give the user some time to explore the application on their own since users have developed some kind of blindness towards anything that pops up right after opening an application...

**Comment by carrotIndustries** [comment]
How about adding another button to the action bar that opens the menu?
2020-12-31-151830_482x506_scrot

**Comment by carrotIndustries** [comment]
> How about adding another button to the action bar that opens the menu?

One downside of this approach is that some tools such as "move" aren't really useful from this menu as they depend on where the cursor is on tool activation. To me at least that's not that big a deal as the main purpose of the menu in this place is to inform users about pressing the spacebar. The info text on top of the menu is supposed to include a link to the preferences to remove the menu button.

**Comment by carrotIndustries** [comment]
> One downside of this approach is that some tools such as "move" aren't really useful from this menu as they depend on where the cursor is on tool activation.

This could be mitigated by hiding tools that depend on the cursor position from that menu, how about this?

**Comment by bob-u** [comment]
I would prefer to see all the available options at all times.  Maybe a notice somewhere within the popup window could inform a user that selection is required for function to work?  Or, gray our functions that are not available.

**Comment by carrotIndustries** [comment]
So this is what we've got now:
2021-07-09-231437_214x158_scrot

Might not be as pretty as some of the other suggestions, but should get the job done.

**Pull request closed without merging**
