### PR TITLE
Added keysequences

### PR DESCRIPTION
**Pull request by atoav**
Added some keysequences where it made sense. Debate and changes very welcome, see #252

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Some thoughts:

 - <kbd>i</kbd> should always be edit (the selected thing). (We don't need <kbd>i p</kbd> and <kbd>i v</kbd> anymore since these are mutually exclusive)
 - Thus, we can't have <kbd>i</kbd> for non-specific edits (such as rules). These could go by <kbd>I</kbd>.
 - We have some conflicts. "Show in pool manager" is <kbd>h p</kbd> and "Smash" is <kbd>h</kbd>. Unfortunately we currently don't check for this and neither action gets triggered since there's no way to tell which one.

Unfortunately, highlighting conflicts isn't easily possible in the preferences window since we don't know which actions are available simultaneously and could cause conflicts.

I might add something similar to the HUD to the bottom of the canvas that'll show the possible key sequence continuations once the user started typing. That thing could also check for conflicts.

**Comment by atoav** [comment]
Okay cool, feel free to change things, as I might be unavailable the next days. If not, I will come back to it in time.

**Comment by atoav** [comment]
Okay I made some changes:
- as suggested I made sure that there is only <kbd>i</kbd> for edit
- as suggested I used <kbd>I</kbd> for all things that edit some sort of unselected context
- I think I resolved the conflicts with <kbd>h</kbd> by using <kbd>u</kbd> for all things that show things
- Added some general secondary shortcuts like <kbd>F1</kbd> for help, <kbd>Ctrl + ,</kbd> for preferences, etc.

I couldn't set a preference for `Frame > Edit Frame properties` there is no dialogue, you might have a look in that one.

**Comment by carrotIndustries** [comment]
> I couldn't set a preference for Frame > Edit Frame properties there is no dialogue, you might have a look in that one.

fixed in 27eaac25ec70dfa8e0416aa02e22a0c4d52394bd

**Comment by carrotIndustries** [comment]
See table below for an overview and my comments

| Action                             | Key sequence | Comments |
|------------------------------------|--------------|----------|
| Move                               | `m`          |          |
| Place junction                     | `p j`        |          |
| Draw line                          | `d l`        |          |
| Delete                             | `Delete`     |          |
| Draw arc                           | `d a`        |          |
| Rotate                             | `r`          |          |
| Mirror X                           | `e`          |          |
| Mirror Y                           | `E`          |          |
| Place pin                          | `p p`        |          |
| Place symbol                       | `p s`        |          |
| Draw net line                      | `n`          |          |
| Place component                    | `p c`        |          |
| Place text                         | `p t`        |          |
| Place net label                    | `b`          |  perhaps `p n`        |
| Disconnect                         | `z`          |          |
| Bend net line                      | `k`          |          |
| Select net segment                 | `plus`       |          |
| Place power symbol                 | `p o`        |          |
| Move net segment to other net      | `v`          |          |
| Move net segment to new net        | `V`          |          |
| Place bus label                    | `p u`        |          |
| Place bus ripper                   | `slash`      | since people don't need bus rippers all the time, `p r` should be fine        |
| Manage buses                       | `I b b`      |          |
| Draw polygon                       | `d y`        |          |
| Enter datum                        | `Return`     |          |
| Move exactly                       | `M`          |          |
| Place pad                          | `p p`        |          |
| Paste                              | `Ctrl-v`     |          |
| Assign part                        | `p b`        |          |
| Place package                      | `p p`        |          |
| Draw track                         | `d t`        |          |
| Place via                          | `p v`        |          |
| Drag and keep slope                | `G`          |          |
| Annotate                           | `a a`        |  perhaps `I a` to make it consistent with other global editors        |
| Smash                              | `h`          |          |
| Unmash                             | `H`          |          |
| Place shape                        | `p s`        |          |
| Edit shape                         | `i s`        |          |
| Import dxf                         | `d x f`      | cute, but inconsistent          |
| Manage net classes                 | `I n`        |          |
| Edit pad                           | `i`          |          |
| Draw polygon rectangle             | `d Y`        |          |
| Draw line rectangle                | `d L`        |          |
| Edit line rectangle                | `i l`        |  just `i`        |
| Edit schematic properties          | `I s`        |          |
| Route track                        | `x`          |          |
| Edit via                           | `i`          |          |
| Rotate arbitrary                   | `R`          |          |
| Add plane                          | `a q`        |          |
| Edit plane                         | `i`          |          |
| Update plane                       | `Ctrl-q`     |          |
| Update all planes                  | `q`          |          |
| Clear plane                        | `Alt-q`      |          |
| Clear all planes                   | `Q`          |          |
| Draw dimension                     | `d d`        |          |
| Route diff. pair                   | `X`          |          |
| Select more                        | `plus`       |          |
| Select more (stop at vias)         | `equal`      |          |
| Drag track                         | `g`          |          |
| Lock                               | `c`          |          |
| Unlock                             | `Alt-c`      |          |
| Unlock all                         | `C`          |          |
| Add vertex                         | `p x`        |          |
| Manage power nets                  | `I p o`      |   why not just `I o`       |
| Place hole                         | `p h`        |          |
| Edit hole                          | `i`          |          |
| Set group                          | `Ctrl-g`     |          |
| Set new group                      | `Ctrl-G`     |          |
| Rename group                       | `Ctrl-Alt-g` |  some desktop environments tend to use Ctrl-Alt for global shortcuts        |
| Clear group                        | `Alt-g`      |          |
| Set tag                            | `Ctrl-t`     |          |
| Set new tag                        | `Ctrl-T`     |          |
| Rename tag                         | `Ctrl-Alt-t` |          |
| Clear tag                          | `Alt-t`      |          |
| Toggle group&tag visibility        | `u u`        |  why `u`?        |
| Copy placement                     | `Ctrl-Alt-c` |          |
| Copy tracks                        | `Ctrl-C`     |          |
| Move up                            | `Up`         |          |
| Move down                          | `Down`       |          |
| Move left                          | `Left`       |          |
| Move right                         | `Right`      |          |
| Line loop to polygon               | `c y`        |  why `c`?        |
| Scale                              | `s`          |          |
| Edit frame properties              | `I f`        |          |
| Add keepout                        | `p c`        |  should be `a k` (consistency with planes)        |
| Place refdes and value             | `p T`        |          |
| Draw polygon circle                | `d c`        |          |
| Draw connection line               | `d n`        |          |
| Undo                               | `Ctrl-z`     |          |
| Redo                               | `Ctrl-y`     |          |
| Redo                               | `Ctrl-Z`     |          |
| Copy                               | `Ctrl-c`     |          |
| Duplicate                          | `Ctrl-d`     |          |
| Place part                         | `p p`        |          |
| Layer up                           | `Page_Up`    |          |
| Layer down                         | `Page_Down`  |          |
| Layer top                          | `1`          |          |
| Layer bottom                       | `2`          |          |
| Layer inner 1                      | `3`          |          |
| Layer inner 2                      | `4`          |          |
| Layer inner 3                      | `5`          |          |
| Layer inner 4                      | `6`          |          |
| Layer inner 5                      | `7`          |          |
| Layer inner 6                      | `8`          |          |
| Layer inner 7                      | `9`          |          |
| Layer inner 8                      | `0`          |          |
| Selection filter                   | `Ctrl-i`     |          |
| Save                               | `Ctrl-s`     |          |
| 3D View                            | `Alt-3`      |          |
| Rules                              | `I r`        |          |
| Run checks                         | `I I`        |          |
| Preferences                        | `Ctrl-P`     |          |
| Preferences                        | `Ctrl-comma` |          |
| Popover                            | `space`      |          |
| Help                               | `question`   |          |
| Help                               | `F1`         |          |
| View all                           | `Home`       |          |
| View all                           | `grave`      |          |
| Selection tool box                 | `S b`        |          |
| Selection tool lasso               | `S l`        |          |
| Selection tool paint               | `S p`        |          |
| Selection qualifier auto           | `S a`        |          |
| Selection qualifier include origin | `S o`        |          |
| Selection qualifier touch box      | `S t`        |          |
| Selection qualifier include box    | `S i`        |          |
| Place on board                     | `p b`        |  conflicts with assign part        |
| Move to other sheet                | `Ctrl-x`     |          |
| Show in browser                    | `h b`        |          |
| Highlight net                      | `u n`        |  why `u`?        |
| Reload netlist                     | `F5`         |          |
| Save and reload netlist            | `Ctrl-S`     |          |
| BOM export window                  | `Ctrl-b`     |          |
| Reload pool                        | `F5`         |  in the future, reload pool might also become available in schematic and board, so better use shift- or ctrl-F5         |
| Flip view                          | `Ctrl-F`     | maybe `v f` to be consistent with the other view actions?         |
| View top                           | `v t`        |          |
| View bottom                        | `v b`        |          |
| Highlight group                    | `u g`        |          |
| Highlight tag                      | `u t`        |          |
| Search                             | `Ctrl-f`     |          |
| Search next                        | `Ctrl-g`     |          |
| Search previous                    | `Ctrl-G`     |          |
| Go to board                        | `Ctrl-Tab`   |  why ctrl-tab and not just `Tab`         |
| Go to schematic                    | `Ctrl-Tab`   |          |
| Show in pool manager               | `u p`        |          |
| Select all                         | `Ctrl-a`     |          |
| PDF export window                  | `Ctrl-p`     |          |
| Backannotate connection lines      | `b n`        |          |

**Comment by atoav** [comment]
I added my own annotations, this is meant to be a "patch"-like list for myself when I chang these things later on

Action | Key sequence | Your comment | My comment |
-- | -- | -- | --
Place net label | b | perhaps p n | kept it because `b` was the default, but can change for consistency with other place stuff
Place bus ripper | slash | since people don't need bus rippers all the time, p r should be fine | Good 
Annotate | a a | perhaps I a to make it consistent with other global editors | Good 
Import dxf | d x f | cute, but inconsistent | Any suggestion here?
Edit line rectangle | i l | just i | Good. Was afraid it would override "Edit via"
Manage power nets | I p o | why not just I o | Good catch
Rename group | Ctrl-Alt-g | some desktop environments tend to use Ctrl-Alt for global shortcuts | Okay, any suggestions? Maybe renaming could be something universal?
Toggle group&tag visibility | u u | why u? | The letter was free and I had no better idea. what else could we use?
Line loop to polygon | c y | why c? | This was a shortcut I had set for personal use, there certainly is something better
Add keepout | p c | should be a k (consistency with planes) | Good
Place on board | p b | conflicts with assign part | good catch, we should find a good short one for this
Highlight net | u n | why u? | I somehow chose `u` for View/Highlight related stuff
Reload pool | F5 | in the future, reload pool might also become available in schematic and board, so better use shift- or ctrl-F5 | how about Ctrl-r ? 
Flip view | Ctrl-F | maybe v f to be consistent with the other view actions? | makes sense
Go to board | Ctrl-Tab | why ctrl-tab and not just Tab | good question, lets do it like that
Go to schematic | Ctrl-Tab |  why ctrl-tab and not just Tab | good question, lets do it like that

**Comment by carrotIndustries** [comment]
f152e2a4ab2d25d2c1c3935a1982841b8685bbc2 adds these keybindings:

|Action | Key sequence | Comments|
|-|-|-|
|Move|`m` | |
|Draw line|`d l` | |
|Delete|`Delete` | |
|Draw arc|`d a` | |
|Rotate|`r` | |
|Mirror X|`e` | |
|Mirror Y|`E` | |
|Place pin|`p p` | |
|Place symbol|`p y` | |
|Draw net line|`n` | |
|Place component|`p c` | |
|Place text|`p t` | |
|Place net label|`b` | |
|Place net label|`p n` | |
|Bend net line|`k` | |
|Select net segment|`plus` | |
|Place power symbol|`p o` | |
|Move net segment to other net|`v` | |
|Move net segment to new net|`V` | |
|Edit symbol pin names|`i` | |
|Place bus label|`p u` | |
|Place bus ripper|`p r` | |
|Draw polygon|`d y` | |
|Enter datum|`Return` | |
|Move exactly|`M` | |
|Place hole|`p h` | |
|Place pad|`p p` | |
|Paste|`Ctrl-v` | |
|Place package|`p p` | |
|Place via|`p v` | |
|Drag and keep slope|`G` | |
|Smash|`h` | |
|Unsmash|`H` | |
|Place shape|`p s` | |
|Edit shape|`i` | |
|Edit pad|`i p` | |
|Draw polygon rectangle|`d Y` | |
|Draw line rectangle|`d L` | |
|Edit line rectangle|`i` | |
|Route track|`x` | |
|Edit via|`i` | |
|Rotate arbitrary|`R` | |
|Edit plane|`i` | |
|Update all planes|`q` | |
|Clear all planes|`Q` | |
|Draw dimension|`d d` | |
|Route diff. pair|`X` | |
|Drag track|`g` | |
|Lock|`c` | |
|Unlock all|`C` | |
|Add vertex|`p x` | |
|Place hole|`p h` | |
|Edit hole|`i` | |
|Move up|`Up` | |
|Move down|`Down` | |
|Move left|`Left` | |
|Move right|`Right` | |
|Swap nets|`s` | |
|Edit keepout|`i` | |
|Place refdes and value|`p r` | |
|Draw connection line|`d c` | |
|Duplicate|`Ctrl-d` | |
|Fix package|`f` | |
|Unfix package|`F` | |
|Undo|`Ctrl-z` | |
|Redo|`Ctrl-y` | |
|Redo|`Ctrl-Z` | |
|Copy|`Ctrl-c` | |
|Place part|`p p` | |
|Layer up|`Page_Up` | |
|Layer down|`Page_Down` | |
|Layer top|`1` | |
|Layer bottom|`2` | |
|Layer inner 1|`3` | |
|Layer inner 2|`4` | |
|Layer inner 3|`5` | |
|Layer inner 4|`6` | |
|Layer inner 5|`7` | |
|Layer inner 6|`8` | |
|Layer inner 7|`9` | |
|Layer inner 8|`0` | |
|Selection filter|`Ctrl-i` | |
|Save|`Ctrl-s` | |
|3D View|`Alt-3` | |
|Preferences|`Ctrl-P` | |
|Popover|`space` | |
|Help|`question` | |
|View all|`Home` | |
|Selection tool box|`S b` | |
|Selection tool lasso|`S l` | |
|Selection tool paint|`S p` | |
|Selection qualifier auto|`S a` | |
|Selection qualifier include origin|`S o` | |
|Selection qualifier touch box|`S t` | |
|Selection qualifier include box|`S i` | |
|Place on board|`p b` | |
|Highlight net|`l` | |
|Reload netlist|`Shift-F5` | |
|Save and reload netlist|`Ctrl-S` | |
|BOM export window|`Ctrl-b` | |
|Reload pool|`F5` | |
|Flip view|`v f` | |
|View top|`v t` | |
|View bottom|`v b` | |
|Search|`Ctrl-f` | |
|Search next|`Ctrl-g` | |
|Search previous|`Ctrl-G` | |
|Go to board|`Tab` | |
|Go to schematic|`Tab` | |
|Select all|`Ctrl-a` | |
|PDF export window|`Ctrl-p` | |
|Select more|`plus` | |
|Select more (stop at vias)|`equal` | |

**Pull request closed without merging**
